version: "3"
services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    mongo:
        image: mongo
        ports:
            - "8081:8081"
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: plutus
            MONGO_INITDB_ROOT_PASSWORD: plutus
            MONGO_INITDB_DATABASE: plutus
networks:
    develop:
